// Per-product confidence in the RECIPE-DERIVED theoretical usage that feeds
// smoothieking.netchef_usage_api.qty_issue.
//
// Provenance: generated by validating netchef-extractor/theoretical.py against
// CrunchTime's own qty_issue (netchef_usage) for all three stores, inventory
// week 2026-07-21..27. The tier is the WORST error seen across the three
// stores, so a product only earns tier A if it held everywhere.
//
// This matters because variance = physical - book, and book carries qty_issue.
// A product whose theoretical usage we model badly will show fake shrink. Any
// surface built on netchef_usage_api MUST show the tier so nobody chases it.
//
// Keep in sync with theoretical.py TIERS when the model changes.

export type Tier = 'A' | 'B' | 'C' | 'D'

// Worst-case error > 25% across stores. Treat their variance as unmodelled.
export const TIER_D: Record<string, string> = {
  P1025: 'Coconut Flakes — worst 385%',
  P1053: 'Goji Berries — worst 98%',
  P1024: 'Cocoa Nibs — worst 57%',
  P1048: 'Foil Sheets — worst 40%',
  P1011: 'Blueberries - Fresh — worst 38%',
  P1117: 'P15 - Stevia — worst 32%',
  P1056: 'Honey — worst 29%',
}

// Worst-case error 10-25%. Directionally useful; don't act on one SKU alone.
export const TIER_C: Record<string, string> = {
  P1082: 'P1 - Non-Fat Milk — worst 25%',
  P1062: 'J7 - Apple Blueberry — worst 23%',
  P1054: 'Granola — worst 22%',
  P1104: 'P16 - Vegan — worst 21%',
  P1034: 'P11 - Date Powder — worst 20%',
  P1083: 'J15 - Milk - Oat — worst 20%',
  P1022: 'E11 - Cinnamon — worst 19%',
  P1066: 'J5 - Pear — worst 19%',
  P1059: 'E3 - Immune Support — worst 19%',
  P1090: 'J1 - Papaya — worst 19%',
  P6415: 'Red Pepper Flakes — worst 18%',
  P1088: 'P13 - Nutrient Blend — worst 17%',
  P6414: 'Chili Garlic Oil — worst 16%',
  P1079: 'E8 - Metabolism Boost — worst 16%',
  P1103: 'P3 - Protein Blend — worst 15%',
  P1069: 'J8 - White Grape Lemon — worst 14%',
  P1064: 'J6 - Apple Pineapple — worst 13%',
  P1058: 'Butter Pecan Ice Cream — worst 13%',
  P1063: 'J2 - Apple Kiwi — worst 13%',
  P1108: 'Raspberry - Frozen — worst 13%',
  P1061: 'J3 - Apple — worst 13%',
  P1044: 'J13 - Electrolyte Blend — worst 12%',
  P1123: 'P2 - Turbinado/Demerara — worst 12%',
}

// Two known one-directional biases in the model, both of which INFLATE
// apparent shrink rather than hide it:
//   * substitutions — a "Sub - Milk - Oat" line adds oat milk but never
//     removes the base milk, so substitutable bases over-count as used
//   * bowl toppings — hand-portioned, so recipe quantities are nominal
export const BIAS_NOTE =
  'Modelled usage over-counts substitutable bases (milks, sweeteners) and ' +
  'hand-portioned bowl toppings, which shows up as overstated shrink.'

export function tierOf(productNumber: string): Tier {
  if (TIER_D[productNumber]) return 'D'
  if (TIER_C[productNumber]) return 'C'
  return 'A'
}

export function tierReason(productNumber: string): string | null {
  return TIER_D[productNumber] ?? TIER_C[productNumber] ?? null
}
